### ISSUE TITLE
State is unknown

### ISSUE THREAD

**Issue by marciej123** [cyberjunky/home-assistant-toon_climate#44] opened 2023-09-01 09:03 UTC
Since a couple of weeks I have the issue that the state is unknown:
![afbeelding](https://github.com/cyberjunky/home-assistant-toon_climate/assets/9057854/3ea932f8-1035-485a-b8a6-4f3984ac480b)

Nothing changed in the network and I'm still able to connect to the toon so network connectivity is okay.

Any clue what could be the issue?

**Comment by rbak69** [comment] 2023-09-10 08:31
Hi @marciej123 I have two Toon devices and both work flawlessly. Have you checked the logs in Home Assistant as they might be able to provide more detail about the cause of the issue.

**Comment by cyberjunky** [comment] 2023-12-23 16:06
Closing because of old ticket, if still an issue please reopen.

**Closed by cyberjunky** 2023-12-23 16:06 UTC
